openapi: "3.0.3"
info:
  title: "paw_arbeidssoker_profilering API"
  description: "paw_arbeidssoker_profilering API"
  version: "1.0.0"
servers:
- url: "https://arbeidssoker-profilering.intern.dev.nav.no"
paths:
  /api/v1/profilering:
    get:
      description: ""
      responses:
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Arbeidssøker ikke funnet"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProfileringDto"
  /api/v1/profilering/standard-innsats:
    get:
      description: ""
      responses:
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Arbeidssøker ikke funnet"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "boolean"
  /internal/isAlive:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "ALIVE"
  /internal/isReady:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "READY"
  /internal/metrics:
    get:
      description: ""
      parameters:
      - name: "name[]"
        in: "query"
        required: false
        schema:
          type: "string"
components:
  schemas:
    ProfileringDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        innsatsgruppe:
          type: "string"
          enum:
          - "STANDARD_INNSATS"
          - "SITUASJONSBESTEMT_INNSATS"
          - "BEHOV_FOR_ARBEIDSEVNEVURDERING"
        opprettet:
          type: "string"
          format: "date-time"
        endret:
          type: "string"
          format: "date-time"