version: '3.9'

services:
  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=profilering

  wiremock:
    image: wiremock/wiremock:2.32.0
    ports:
      - "8090:8080"
    volumes:
      - ./wiremock:/home/wiremock/mappings/

  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.3.1'
    restart: always
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.6
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      JSON_CONFIG: >
        {
          "interactiveLogin": true,
          "httpServer": "NettyWrapper",
          "tokenCallbacks": [
            {
              "issuerId": "default",
              "tokenExpiry": 15780000,
              "requestMappings": [
                {
                  "requestParam": "scope",
                  "match": "openid somescope",
                  "claims": {
                    "sub": "admin@arbeidssokerregistrering",
                    "aud": ["paw-arbeidssoker-profilering"]
                  }
                },
                {
                  "requestParam": "scope",
                  "match": "default",
                  "claims": {
                    "aud": ["paw-arbeidssoker-profilering"]
                  }
                }
              ]
            }
          ]
        }
