apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: paw-arbeidssoker-profilering-unleash
  namespace: paw
  labels:
    "team": "paw"
spec:
    unleashInstance:
      apiVersion: unleash.nais.io/v1
      kind: RemoteUnleash
      name: paw
    secretName: paw-arbeidssoker-profilering-unleash-api-token
    environment: development
